#!/usr/bin/env python
# coding: utf-8

# # Applications of representation theory to physics problems
# 
# Representation theory can be used in many problems in physics to simplify calculations:
# - molecular physics
# - crystallography
# - quantum mechanics
# - particle physics
# - ...
# - any system with a symmetry
# 
# ## Main example: vibrations of water molecules
# 
# >picture
# 
# This molecule sits in the $y-z$ plane with the $x$-axis pointing towards the reader. 
# 
# There are four symmetries of this molecule:
# - $E$: identity
# - $C_2$: rotation by $\pi$ in the $x-y$ plane
# - $\sigma_{yz}$: reflection with respect to the $y-z$ plane
# - $\sigma_{xz}$: reflection with respect to the $x=z$ plane located at the oxygen atom
# 
# Multiplication table of this group is:
# 
# $$
# \begin{array}{c||c|c|c|c|}
# \star&E&C_2&\sigma_{yz}&\sigma_{xz}\\
# \hline
# \hline
# E&E&C_2&\sigma_{yz}&\sigma_{xz}\\
# \hline
# C_2&C_2&E&\sigma_{xz}&\sigma_{yz}\\
# \hline
# \sigma_{yz}&\sigma_{yz}&\sigma_{xz}&E&C_2\\
# \hline
# \sigma_{xz}&\sigma_{xz}&\sigma_{yz}&C_2&E
# \end{array}
# $$
# 
# This group of symmetries is called $C_{2\nu}$ and it is isomorphic to the group $\mathbb{Z}_2\times \mathbb{Z}_2$:
# 
# $$
# \mathbb{Z}_2\times \mathbb{Z}_2=\{(0,0),(0,1),(1,0),(1,1)\}
# $$
# 
# with the binary operation given by addition of these two-dimensional vectors modulo 2.
# 
# In the following we will use the character table for $C_{2\nu}$. The group $C_{2\nu}$ is abelian with four elements, each of which gives one conjugacy class, implying that there are four irreducible representations, all of them one-dimensional:
# 
# $$
# \begin{array}{c||c|c|c|c|}
# \star&E&C_2&\sigma_{yz}&\sigma_{xz}\\
# \hline
# \hline
# A_1&1&1&1&1\\
# \hline
# A_2&1&1&-1&-1\\
# \hline
# B_1&1&-1&1&-1\\
# \hline
# B_2&1&-1&-1&1
# \end{array}
# $$
# 
# Looking back at the water molecule, we can construct the representation generated by the nine vectors in the figure above: $(x_O,y_O,z_O,x_H,y_H,z_H,\tilde{x}_H,\tilde{y}_H,\tilde{z}_H)$. This provides the following nine dimensional representation $\Gamma_9$:
# 
# $$
# M_E=\begin{pmatrix}1&0&0&0&0&0&0&0&0\\0&1&0&0&0&0&0&0&0\\0&0&1&0&0&0&0&0&0\\0&0&0&1&0&0&0&0&0\\0&0&0&0&1&0&0&0&0\\0&0&0&0&0&1&0&0&0\\0&0&0&0&0&0&1&0&0\\0&0&0&0&0&0&0&1&0\\0&0&0&0&0&0&0&0&1\end{pmatrix} \qquad  M_{C_2}=\begin{pmatrix}-1&0&0&0&0&0&0&0&0\\0&-1&0&0&0&0&0&0&0\\0&0&1&0&0&0&0&0&0\\0&0&0&0&0&0&-1&0&0\\0&0&0&0&0&0&0&-1&0\\0&0&0&0&0&0&0&0&1\\0&0&0&-1&0&0&0&0&0\\0&0&0&0&-1&0&0&0&0\\0&0&0&0&0&1&0&0&0\end{pmatrix}
# $$

# In[ ]:




