#!/usr/bin/env python
# coding: utf-8

# # Group homomorphisms and group actions
# 
# ## Group homomorphism
# 
# In many cases it is possible to have groups that are defined in a completely unrelated way but they have the same Cayley tables. For example, cyclic groups $C_n={e,g,g^2,\ldots,g^{n-1}}$ can be defined in the following independent ways:
# - as the subgroup of $S_n$ generated by $(123\ldots n)$
# - as the subgroup of $2\times 2$ invertible matrices generated by $\begin{pmatrix}\cos(\frac{2\pi}{n})&\sin(\frac{2\pi}{n})\\-\sin(\frac{2\pi}{n})&\cos(\frac{2\pi}{n})\end{pmatrix}$
# - as the group $\mathbb{Z}_n$ with addition module $n$.
# 
# Note that these are all different, but their multiplication tables are the same, and we say that as groups they are the same. What can that mean? It must mean that at least there is a one-to-one map between their elements, e.g. take $n=5$ and make the table:
# 
# $$
# \begin{array}{c|ccc}
# \mbox{element in }C_n& \mbox{permutations}&\mbox{matrices}& (\mathbb{Z}_n,+\,(\mathrm{mod}\,\ n))\\\hline
# e&e&\begin{pmatrix}1&0\\ 0&1\end{pmatrix}&0\\
# g&(12345)&\begin{pmatrix}\cos(\frac{2\pi}{5})&\sin(\frac{2\pi}{5})\\ -\sin(\frac{2\pi}{5})&\cos(\frac{2\pi}{5})\end{pmatrix}&1\\
# g^2&(13524)&\begin{pmatrix}\cos(\frac{4\pi}{5})&\sin(\frac{4\pi}{5})\\-\sin(\frac{4\pi}{5})&\cos(\frac{4\pi}{5})\end{pmatrix}&2\\
# g^3&(14253)&\begin{pmatrix}\cos(\frac{6\pi}{5})&\sin(\frac{6\pi}{5})\\-\sin(\frac{6\pi}{5})&\cos(\frac{6\pi}{5})\end{pmatrix}&3\\
# g^4&(15432)&\begin{pmatrix}\cos(\frac{8\pi}{5})&\sin(\frac{8\pi}{5})\\-\sin(\frac{8\pi}{5})&\cos(\frac{8\pi}{5})\end{pmatrix}&4\\
# \end{array}
# $$
# 
# But to say the groups are "the same" we need to make sure that the multiplication tables are the same in all these cases. How to make if precise and general? Suppose that we have two groups, $(G,\star)$ and $(H,\cdot)$, that we suspect to be "the same". That means there should be a map
# 
# $$
# \Theta:G\to H
# $$
# 
# that is a one-to-one map (i.e. a bijection) telling us how to identify any $g\in G$ with its partner $\Theta(g)\in H$
# 
# Additionally, it should not matter whether we perform the "multiplication" first in $G$ and then go to $H$, or we go to $H$ first and multiply the elements there. In other words we demand that:
# 
# $$
# \Theta(g_1\star g_2)=\Theta(g_1)\cdot \Theta(g_2)
# $$
# 
# ```{admonition} Definition (Group homomorphism)
# :class: definition
# 
# A **group homomorphism** from $(G,\star)$ to $(H,\cdot)$ is a function $\Theta:G\to H$ such that for all $g_1,g_2\in G$ it holds that
# 
# $$
# \Theta(g_1\star g_2)=\Theta(g_1)\cdot \Theta(g_2)
# $$
# 
# ```
# 
# Not all functions between two groups are group homomorphisms. We can however find a few of them using the groups that we defined in the previous lecture.
# 
# ```{admonition} Examples (Group homomorphism)
# :class: example
# 
# - For any groups $G$ and $H$ there is always at least one group homomorphism, called the *trivial homomorphism* that is defined as $\Theta(g)=e_H$ for all $g\in G$. This homomorphism takes all elements of $G$ and maps them to the identity element in $H$.
# 
# - The map 
# 
# $$
# \Theta: (\mathbb{Z},+)\to (\mathbb{Z},+\,(\mathrm{mod}\,\, n))
# $$
# 
# defined as $\Theta(z)=z$, is a group homomorphism.
# 
# - The map $\Theta:S_n\to S_2$ defined as: for $\sigma\in S_n$:
# 
# $$
# \Theta(\sigma)=\begin{cases}e&\mbox{if }\sigma \mbox{ is even}\\(12)&\mbox{if }\sigma \mbox{ is odd}\end{cases}
# $$
# 
# ```
# 
# If we find a homomorphism that is additionally a bijection then we call such homomorphism an isomorphism:
# 
# ```{admonition} Definition (Isomorphism)
# :class: definition
# 
# A group homomorphism $\Theta:G\to H$ is an **isomorphism** if it is one-to-one and onto (it is a bijection). If there exists an isomorphism between two groups $G$ and $H$, then we say that these groups are **isomorphic**.
# ```
# 
# Homomorhisms provide a good way to generate subgroups of a given group. Let us first define what we mean by the kernel and the image.
# 
# ```{admonition} Definition (Kernel of a homomorphism)
# :class: definition
# 
# Let $G$ and $H$ be groups, and $\Theta:G\to H$ be a group homomorphism. The **kernel of homomorphism $\Theta$** is the set of all elements in $G$ such that:
# 
# $$
# \mbox{ker}\Theta=\{g\in G:\Theta(g)=e_H\}
# $$
# ```
# 
# ```{admonition} Proposition
# :class: proposition
# 
# Let $\Theta:G\to H$ be a group homomorphism. Then the kernel of $\Theta$ is a subgroup of $G$.
# ```
# 
# ```{admonition} Examples (Kernel of a homomorphism)
# :class: example
# 
# - For $\theta:\mathbb{Z}\to \mathbb{Z}_n$ defined as $\Theta(z)=z$, the kernel is :
# 
# $$
# \mbox{ker}\Theta=n\mathbb{Z}
# $$
# 
# that is the set of all integers divisible by $n$.
# 
# - For $\Theta:S_n\to S_2$ defined above, the kernel is:
# 
# $$
# \mbox{ker}\Theta=\{\sigma\in S_n:\sigma \mbox{ is even}\}=A_n
# $$
# ```
# 
# ```{admonition} Definition (Image of a homomorphism)
# :class: definition
# 
# Let $\Theta:G\to H$ be a group homomorphism. Then the **image of $\Theta$** is the set:
# 
# $$
# \mbox{im}\Theta=\{\Theta(g):g\in G\}
# $$
# 
# ```
# 
# 
# ```{admonition} Example (Image of a homomorphism)
# :class: example
# 
# - For $\Theta:S_3\to S_4$ defined as: for $\sigma=\begin{pmatrix}1&2&3\\ \sigma(1)&\sigma(2)&\sigma(3)\end{pmatrix}$ we have $\Theta(\sigma)=\begin{pmatrix}1&2&3&4\\ \sigma(1)&\sigma(2)&\sigma(3)&4\end{pmatrix}$. Then the image of $\Theta$ is:
# 
# $$
# \mbox{im}\Theta=\{\sigma\in S_4:\sigma(4)=4\}
# $$
# 
# 
# ```
# 
# ## Group actions
# 
# ```{admonition} Definition (Group action)
# :class: definition
# 
# We say that a group $(G,\star)$ acts on a set $X$ if there is a map:
# 
# $$
# G\times X\to X\qquad (g,x)\mapsto g.x
# $$
# 
# such that 
# - $e.x=x$ for all $x ain X$, where $e$ is the identity element in $G$
# - $(g\star h).x=g.(h.x)$ for all $x\in X$ and all $g,h\in G$
# 
# ```
# 
# The conditions in this definition mean that:
# - the group identity element "leaves all elements of the set unchanged"
# - the action of the group on the set is compatible with the product in the group
# 
# ```{admonition} Examples (Group action)
# :class: example
# 
# - The group of $2\times 2$ invertible matrices $GL_2(\mathbb{R})$ acts on $\mathbb{R}^2$ by matrix multiplication. In particular, we can define a map:
# 
# $$
# GL_2(\mathbb{R})\times \mathbb{R}^2 \to \mathbb{R}^2\qquad (A,v)\mapsto A v
# $$
# 
# It obeys both conditions in the definition of the group action:
# a) $\mathbb{I}_2 v=v$, where $v\in \mathbb{R}^2$ and $\mathbb{I}_2$ is the identity matrix;
# b) $(AB)v=A(Bv)$ for a pair of matrices $A,B$
# 
# - Let $S_n$ be the set of all permutations of $n$ objects -- the symmetric group. Then $S_n$ acts on the set $X_n=\{1,2,\ldots,n\}$ in a natural way:
# 
# $$
# \sigma.i=\sigma(i)\in X_n
# $$
# 
# for all $\sigma\in S_n$. It is easy to check that both conditions in the definition of group action are satisfied.
# 
# 
# ```
# 
# 

# In[ ]:




